info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
server:
  port:
    '${BACKEND_PORT:8884}'
  compression:
    enabled: on
    min-response-size: 200
    # Define the list of compressible Mime Types
    compressibleMimeTypes:
      - application/json # JSON data
      - application/xml # XML data
      - text/html # HTML content
      - text/xml # XML content
      - text/plain # plain text content
      - image/png # PNG images
      - image/jpeg # JPEG images
      - image/gif # GIF images
spring:
#  activemq:
#    broker-url: '${MQ_URL:tcp://10.10.2.74:61616}'
#    user: '${MQ_USER:artemis}'
#    password: '${MQ_PASS:artemis}'
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: idmed
#            client-secret: 'Xr3spPYYXSUTQ8BoawtPXJjprsCnGNIA' # for confidential clients
#            authorization-grant-type: 'authorization_code'
#            redirect-uri: 'https://idmedreg.csaude.org.mz/login/oauth2/code/keycloak'
#            scope: 'openid, profile, email'
#            provider:
#              keycloak:
#                issuer-uri: https://auth.csaude.org.mz/realms/healthapps-dev
#                  resourceserver:
#                    jwt:
#                      issuer-uri: https://auth.csaude.org.mz/realms/healthapps-dev
  jms:
    listener:
      acknowledge-mode: auto
grails:
  cors:
    enabled: true
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      multipartForm: multipart/form-data
      pdf: application/pdf
  controllers:
    defaultScope: singleton
  urlmapping:
    cache:
      maxsize: 1000000
  converters:
    encoding: UTF-8
  databinding:
    dateFormats:
      - "yyyy-MM-dd'T'HH:mm:ss.SSSX"
      - "yyyy-MM-dd'T'HH:mm:ss"
      - "yyyy-MM-dd"
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  plugin :
    auditLog :
      auditDomainClassName: 'mz.org.fgh.sifmoz.backend.auditTrail.AuditTrail'
      verbose: false
      verboseEvents: [AuditEventType.UPDATE, AuditEventType.INSERT, AuditEventType.DELETE]
      failOnError: true
      excluded: ['version', 'lastUpdated', 'lastUpdatedBy']
      mask: ['password']
      logIds: true
      stampEnabled: true
dataSource:
  driverClassName: org.postgresql.Driver
  dialect: hibernate.MyPostgreSQLDialect
  username: '${DB_USER:postgres}'
  password: '${DB_PASS:postgres}'
  useraccess: '${BACKEND_USER:iDMEDSYNC}'
  userpassaccess: '${BACKEND_PASS:iDMED123}'
  pooled: true
  jmxExport: true
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://localhost:9876/coalane
  test:
    dataSource:
      dbCreate: update
      url: jdbc:postgresql://db:5432/idmed
  production:
    dataSource:
      dbCreate: update
      url: '${DB_URL}'

